apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nacos
  name: nacos
  namespace: env-test
spec:
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - image: nacos/nacos-server:latest
        name: nacos
        env:
        - name: MODE
          value: standalone
        - name: JVM_XMS
          value: 256m
        - name: JVM_XMX
          value: 256m
        - name: JVM_XMN
          value: 128m
        ports:
        - containerPort: 8848
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: env-test
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
  - port: 8848
    targetPort: 8848
    nodePort: 38848